name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy-pypi:
    name: Build and publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Set up python environment
        run: |
          pip3 install -e .
          pip3 install setuptools wheel twine
      - name: Build
        run: python -m build
      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
